### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by L0rdLogan** [modul8co/hikvision-nvr-events#3]
**Describe Your Problem:**
Need help setting it up/ports etc

**Logs:**
11/8/2022, 1:24:49 PM] [Hikvision NVR Events] Could not load channels Error: connect ECONNREFUSED 192.168.1.60:8080
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.60',
  port: 8080,
  name: 'RequestError',
  data: undefined,
  path: '/ISAPI/System/Video/inputs/channels',
  status: -1,
  headers: {},
  res: {
    status: -1,
    statusCode: -1,
    statusMessage: null,
    headers: {},
    size: 0,
    aborted: false,
    rt: 234,
    keepAliveSocket: false,
    data: undefined,
    requestUrls: [ 'http://192.168.1.60:8080/ISAPI/System/Video/inputs/channels' ],
    timing: null,
    remoteAddress: '',
    remotePort: '',
    socketHandledRequests: 1,
    socketHandledResponses: 0
```
Show the Homebridge logs here, remove any sensitive information.
```

    "dvr": true,
    "host": "192.168.1.60",
    "port": 8080,
    "username": "xxxxxx",
    "password": "xxxxxxxx",
    "motionurl": "http://192.168.1.60:8080/motion",
    "platform": "Hikvision NVR Events"

```json


**Screenshots:**


**Environment:**

* **1.0.2**:
* **Homebridge Version**: 1.5.1 -->
* **Node.js Version**: < 16.18.0 -->
* **NPM Version**: <Unknown -->
* **Operating System**: Docker

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by modul8co** [comment]
Hello, which model Hikvision do you have?

**Comment by L0rdLogan** [comment]
Hi,

It's a DVR which the cameras connect to. It's a DS-7608NI-K2/8P(D48434898)

**Comment by modul8co** [comment]
http://192.168.1.60:8080/ISAPI/ContentMgmt/InputProxy/channels

http://192.168.1.60:8080/ISAPI/System/Video/inputs/channels

Can you try opening these links in a web browser on your network?

**Comment by L0rdLogan** [comment]
Will do when I'm home, I'll come back later

**Comment by modul8co** [comment]
OK, I suspect that model is an NVR - rather than a DVR. So the issue may be DVR: true in your config.

If I'm right, the first link should work and the second won't.

**Comment by L0rdLogan** [comment]
> http://192.168.1.60:8080/ISAPI/ContentMgmt/InputProxy/channels
> 
> 
> 
> http://192.168.1.60:8080/ISAPI/System/Video/inputs/channels
> 
> 
> 
> Can you try opening these links in a web browser on your network?

Those links did not work unfortunately on my local network 

![image](https://user-images.githubusercontent.com/5092548/201177898-b49e1682-e2c3-4b26-a99b-bdfa70bf2695.png)

**Comment by modul8co** [comment]
Ok, does http://192.168.1.60:8080 work?

**Comment by L0rdLogan** [comment]
No, but I can get to the web interface with port 443

Here's the ports if it helps you

![image](https://user-images.githubusercontent.com/5092548/201204059-2b79d783-38fe-4e66-a1ca-072727dd6f27.png)

**Comment by L0rdLogan** [comment]
I do get a different error if I try and use port 443 in the JSON config

[11/10/2022, 8:57:50 PM] [Hikvision NVR Events] Could not load channels Error [ResponseError]: socket hang up, GET http://192.168.1.60:443/ISAPI/ContentMgmt/InputProxy/channels -1 (connected: true, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}
    at connResetException (node:internal/errors:711:14)
    at Socket.socketOnEnd (node:_http_client:518:23)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNRESET',
  data: undefined,
  path: '/ISAPI/ContentMgmt/InputProxy/channels',
  status: -1,
  headers: {},
  res: {
    status: -1,
    statusCode: -1,
    statusMessage: null,
    headers: {},
    size: 0,
    aborted: false,
    rt: 523,
    keepAliveSocket: false,
    data: undefined,
    requestUrls: [ 'http://192.168.1.60:443/ISAPI/ContentMgmt/InputProxy/channels' ],
    timing: null,
    remoteAddress: '192.168.1.60',
    remotePort: 443,
    socketHandledRequests: 1,
    socketHandledResponses: 0

**Comment by L0rdLogan** [comment]
I also tried port 8000


[11/10/2022, 9:01:59 PM] [Hikvision NVR Events] Could not load channels Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
  name: 'ResponseError',
  data: undefined,
  path: '/ISAPI/ContentMgmt/InputProxy/channels',
  status: -1,
  headers: {},
  res: {
    status: -1,
    statusCode: -1,
    statusMessage: null,
    headers: {},
    size: 0,
    aborted: false,
    rt: 1680,
    keepAliveSocket: false,
    data: undefined,
    requestUrls: [
      'http://192.168.1.60:8000/ISAPI/ContentMgmt/InputProxy/channels'
    ],
    timing: null,
    remoteAddress: '192.168.1.60',
    remotePort: 8000,
    socketHandledRequests: 1,
    socketHandledResponses: 0

**Comment by modul8co** [comment]
According to your config, your port should be 80.

Can you try that and let me know?

**Comment by modul8co** [comment]
http://192.168.1.60:80/ISAPI/ContentMgmt/InputProxy/channels

**Comment by modul8co** [comment]
Also - just a note: your ‘motion’ URL should point to your homebridge instance where you would like the motion alert to trigger ffmpeg, for example on mine it’s http://localhost:8080/motion (I have configured ffmpeg to listen on port 8080)

**Comment by L0rdLogan** [comment]
Okay - i'm getting somewhere, this is on Port 80, maybe the motion URL? homebridge is in a docker on a synology, so i'm using Localhost:8080, I'm not sure if it has to match?

[Hikvision NVR Events] Could not load channels TypeError: Cannot read properties of undefined (reading 'InputProxyChannel')
    at /homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/src/platform.ts:58:42
    at Parser.<anonymous> (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (node:events:513:28)
    at SAXParser.onclosetag (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/homebridge/node_modules/@modul8co/homebridge-hikvision-nvr-events/node_modules/xml2js/lib/parser.js:5:59)

I have FFMeg installed as I use homebridge for my Unifi camera

**Comment by modul8co** [comment]
Do you mind copying/pasting the output from this URL?

http://192.168.1.60:80/ISAPI/ContentMgmt/InputProxy/channels

**Comment by L0rdLogan** [comment]
Webpage displays “
Moved Temporarily


The document has moved here<https://192.168.1.60/ISAPI/ContentMgmt/InputProxy/channels>.


Webs at :: Port 80”

After login

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by modul8co** [comment]
Under network > Advanced settings - can you confirm if you have SSL enabled or not?

**Comment by L0rdLogan** [comment]
I do have it enabled, shall I try turn it off?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by modul8co** [comment]
Yes please. The redirect is expecting the access to be done via SSL which the plugin doesn't support as yet.

**Comment by L0rdLogan** [comment]
Okay, so with HTTPS off, I get this:

<?xml version="1.0" encoding="UTF-8" ?> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannelList version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema" size="2">
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>1</id> 
  <name>Front Right</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.3</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>2</id> 
  <name>Front Left</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.12</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>3</id> 
  <name>Rear Right</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.4</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>4</id> 
  <name>Rear Left</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.13</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>5</id> 
  <name>Garage</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.5</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <InputProxyChannel>
  <id>6</id> 
  <name>Left Side gate</name> 
[-](https://github.com/modul8co/hikvision-nvr-events/issues/3#) <sourceInputPortDescriptor>
  <proxyProtocol>HIKVISION</proxyProtocol> 
  <addressingFormatType>ipaddress</addressingFormatType> 
  <ipAddress>192.168.254.20</ipAddress> 
  <managePortNo>8000</managePortNo> 
  <srcInputPort>1</srcInputPort> 
  <userName>admin</userName> 
  <connMode>plugplay</connMode> 
  <streamType>auto</streamType> 
  <deviceID /> 
  </sourceInputPortDescriptor>
  <certificateValidationEnabled>false</certificateValidationEnabled> 
  <defaultAdminPortEnabled>true</defaultAdminPortEnabled> 
  <enableAnr>false</enableAnr> 
  <enableTiming>true</enableTiming> 
  </InputProxyChannel>
  </InputProxyChannelList>

**Comment by modul8co** [comment]
OK, the plugin should work now with port 80 :-)

**Comment by L0rdLogan** [comment]
With HTTPS/SSL OFF, I get this:

![image](https://user-images.githubusercontent.com/5092548/201329812-9bff254d-1d6e-47a1-a804-e28da0b5dadc.png)

So i'll test it now to see if it'll work

P.S, I am a noob, so I appreciate the help - maybe add a FAQ or little Instructions saying SSL needs to be off :) - Not a command, just a suggestion

Edit 1: It works, so now I feel dumb 🗡️ 

![image](https://user-images.githubusercontent.com/5092548/201330589-41deaeee-d8d8-458d-97e8-6bc2bd14eafd.png)


I cannot see the camera in Home with this plugin though can I? is that the other plugin?

Just based on the name, i'm probably being stupid again

Thank you so much for the help

**Comment by modul8co** [comment]
Great idea, I'll add that to the readme. Happy you got it working :-)

To see the cameras, you need to configure them in FFMPEG

You also need to configure the ffmpeg listening port to say, 8080, and then http://localhost:8080/motion in the config for motion URL. 

Eg, this is mine:

This plugin setup:

        {
            "host": "192.168.1.100",
            "port": 8080,
            "username": "",
            "password": "",
            "motionurl": "http://localhost:8080/motion",
            "platform": "Hikvision NVR Events"
        },

**Comment by modul8co** [comment]
{
            "name": "Camera-ffmpeg",
            "porthttp": 8080,
            "cameras": [
                {
                    "name": "Lounge Terrace",
                    "motion": true,
                    "motionTimeout": 60,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i rtsp://user:pass@192.168.1.100/Streaming/Channels/101",
                        "stillImageSource": "-i http://user:pass@192.168.1.100:8080/ISAPI/Streaming/channels/101/picture",
                        "maxWidth": 0,
                        "maxHeight": 0,
                        "maxFPS": 0
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

**Comment by modul8co** [comment]
You can find the IP addresses of your cameras in the extract you pasted above, and add them with matching names to FFMPEG.

Then, when the cameras detect motion, the correct motion sensor will be triggered.

**Comment by L0rdLogan** [comment]
> You can find the IP addresses of your cameras in the extract you pasted above, and add them with matching names to FFMPEG.
> 
> Then, when the cameras detect motion, the correct motion sensor will be triggered.

Thank you very much, I will try that

**Comment by modul8co** [comment]
For example, your first camera config in FFMPEG should look like this:

{
"name": "Front Right",
"motion": true,
"motionTimeout": 60,
"unbridge": true,
"videoConfig": {
"source": "-i rtsp://user:pass@192.168.1.60/Streaming/Channels/101",
"stillImageSource": "-i http://user:pass@192.168.1.60:80/ISAPI/Streaming/channels/101/picture",
"maxWidth": 0,
"maxHeight": 0,
"maxFPS": 0
}

**Comment by L0rdLogan** [comment]
![image](https://user-images.githubusercontent.com/5092548/201332276-5dc06aab-8702-4779-bc9f-d2c6fe7a8a80.png)

This plugin works and I can see them live (Previously, I couldn't, I was only seeing snapshots and it would indefinately spin) - I'll do more testing to ensure the motion triggering works. if it doesn't work, i'll manually configure each, following your example

**Comment by modul8co** [comment]
Awesome! Happy we sorted it. Enjoy!
